# Sharechain links used by cloud content/update fetchers.

donation_leaderboard.url=http://sharechain.qq.com/ad02296d23d23f928b07f3a83677d166
update_primary.url=http://sharechain.qq.com/e212f77e7f2b144573436443a08175fc
update_changelog.url=http://sharechain.qq.com/eba665b08b447f76c5a267af0fceeeea